name: Entregables

on: 
    push:
      branches: [ main ]
jobs:
  build:
    runs-on: windows-lastest
    permissions:
      contents: write

    steps:
      - name: Paso 1 - Checkout repositorio
        uses: actions/checkout@v4
      - name: Paso 2 - Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.2'
      - name: Paso 3 - Crear un entorno virtual
        run: python -m venv venv
      - name: Paso 4 - Activar entorno virtual
        run: ./venv/Scripts/activate
      - name: Paso 5 - Ejecutar Script
        run: python test.py
